version: '2'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.16.3"
    ports:
      - "9200:9200"
  kibana:
    image: "docker.elastic.co/kibana/kibana:7.16.3"
    # volumes:
    #   - ./kibana.yaml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
  webapp:
    image: "azraaibaharin/xendittrial:latest"
    ports:
      - "49160:8080"

