apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: xendittrial
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: discovery.type
          value: "single-node"
        ports:
        - containerPort: 9200
        - containerPort: 9300
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-svc
  namespace: xendittrial
spec:
  type: NodePort
  selector:
    app: elasticsearch-svc
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 30008