apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: xendittrial
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.16.3
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch-svc:9200"
        ports:
        - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-svc
  namespace: xendittrial
spec:
  type: NodePort
  selector:
    app: kibana-svc
  ports:
  - port: 5601
    targetPort: 5601
    nodePort: 30009