apiVersion: apps/v1
kind: Deployment
metadata:
  name: xendittrial-app
  namespace: xendittrial
  labels:
    app: xendittrial-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xendittrial-app
  template:
    metadata:
      labels:
        app: xendittrial-app
    spec:
      containers:
      - name: xendittrial-app
        image: azraaibaharin/xendittrial:v0.1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch-svc:9200"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: xendittrial-app-svc
  namespace: xendittrial
spec:
  type: NodePort
  selector:
    app: xendittrial-app
  ports:
  - port: 9080
    targetPort: 8080
    nodePort: 30007